### ISSUE TITLE
Feature Request: store content

### ISSUE THREAD

**Issue by pajoma** [mumi/entitygraph-client#3]
Please support the following operations

## SetValue()
Calls set_value with content_type "text/plain"
Parameters: 
* Entity Identifier
* Property (should be qualified URL, so instead of prefixed key "sdo.text" it should be "https://schema.org/text"
* Language (defaults to "en")
* Value (validate, not longer then 255 chars)
* Datatype (optional, defaults to "xsd:string", see https://rdflib.readthedocs.io/en/stable/rdf_terms.html#literals) 
* Application (optional)

## SetContent()  
Calls set_value with content_type "application/octet-stream"
Parameters: 
* Entity Identifier
* Property (should be qualified URL, so instead of prefixed key "sdo.text" it should be "https://schema.org/text"
* Language (optional, defaults to "en" for text)
* Content (can be file, path, binary, string)
* Filename (optional, can be random string)
* Application (optional)

**Comment by mumi** [comment]
7535cbc18b40bd32ae5d255ca25d3e75075a0405

[Application().]Entity().set_value(property: str, value: str, language: str = 'en')
[Application().]Entity().set_content(property: str, content: Path | BinaryIO | TextIO | bytes | str, filename: str = None)
